### ISSUE TITLE
Frogger

### ISSUE THREAD

**Issue by jorisvaneijnatten** [jlonij/frame-generator#3]
Frogger does not work. The error "Frog data invalid, skipping document!" is repeated for each document. This is the error message:

Processing regular expressions ...
Processing file: regex.csv
Number of regular expressions: 76
Processing stop words ...
Processing file: stopwords.dutch.snowball.txt
Processing file: stop_words_limited.txt
Number of stop words: 346
Processing documents ...
Processing file: <>
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Processing file: <>
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
Frog data invalid, skipping document!
etc
etc
etc

**Comment by jlonij** [comment]
Frog server restarted and working again.
